version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mmnsin210606?
      MYSQL_DATABASE: ptrainer_users
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: create_admin_microservice
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "90:90"

  second_app:
    build: C:/Users/Mateo/Documents/UCE/2024 - 2025/distribuida/FinalProject/Authenticator/Login/.
    container_name: login_microservice
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env
    ports:
      - "80:80"

  third_app:
    build: C:/Users/Mateo/Documents/UCE/2024 - 2025/distribuida/FinalProject/Authenticator/CreateUser/.
    container_name: create_user_microservice
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"

  fourth_app:
    build: C:/Users/Mateo/Documents/UCE/2024 - 2025/distribuida/FinalProject/Authenticator/GetUserFromToken/.
    container_name: get_user_from_token_microservice
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8080:8080"

  fifth_app:
    build: C:/Users/Mateo/Documents/UCE/2024 - 2025/distribuida/FinalProject/Authenticator/ChangePassword/.
    container_name: change_password_microservice
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8078:8078"

volumes:
  mysql_data:
